# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "TOBIAS"

# URL
baseurl:            ""
url: ""
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Social Media
twitter_username: tobylunt

# Assets
assets:
  sources:
    - _assets/fonts
    - _assets/font-awesome-4.3.0
    - _assets/img

# Markdown
markdown:           rdiscount

# Navigation
nav:
  - name:           "About"
    href:           "/about"
  - name:           "CV"
    href:           "/cv"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
      
include: [
  ".htaccess",
  ".htpasswd"
]